### ISSUE TITLE
Spelling Mistake in Documentation on Plane.so Website

### ISSUE THREAD

**Issue by ar-mohanty** [makeplane/docs#106]
I’ve noticed a spelling mistake in the documentation on the Plane.so website. The error is located in Quick Start > creating cycles section, and it reads “pendind” where it should be “pending”.

**Expected Result**: The text should be “pending”

**Actual Result**: The text currently reads “pendind”

### **Additional Information:**

**URL**: https://docs.plane.so/introduction/quickstart

**Screenshots**: 
![image](https://github.com/user-attachments/assets/6a2a2017-5148-46a6-b31a-42429638ef73)
![image](https://github.com/user-attachments/assets/d8cd3eac-1cbe-4af0-8a6b-69c395b460f4)

**Comment by danciaclara** [comment]
thanks for pointing it out @ar-mohanty. will fix it.
