### ISSUE TITLE
bug: Docker Compose setup instructions outdated: menu options mismatch

### ISSUE THREAD

**Issue by DeclanE47** [makeplane/docs#117]
## Description
The current Docker Compose setup instructions in the documentation contain outdated information regarding the available menu options. This discrepancy may confuse users trying to set up or manage their Plane instance.

### Current Behavior
The documentation states:
- "Again the `options [1-6]` will be popped up"
- The "Exit" option is listed as option 6

<img width="739" alt="image" src="https://github.com/user-attachments/assets/99b4ef92-950b-4c2a-836f-2ee9d9aa9ae4">

### Expected Behavior
The documentation should reflect the current setup script behavior:
- "Again the `options [1-8]` will be popped up"
- The "Exit" option should be listed as option 8

### Steps to Reproduce
1. Navigate to the Docker Compose setup instructions in the documentation
2. Compare the documented menu options with the actual options presented by the setup script

#116 fix docs: Update Docker Compose setup menu options from 1-6 to 1-8

**Comment by DeclanE47** [comment]
Fix in PR #116

**Comment by danciaclara** [comment]
Resolved
