### ISSUE TITLE
bug: the link in the index.md for self-hosting in the master branch is not working.

### ISSUE THREAD

**Issue by karim-hammami** [makeplane/docs#48]
![docs](https://github.com/makeplane/docs/assets/73858095/23d6bfb3-ed6d-4afa-866f-70f44085e69d)
the link in the index.md for self-hosting in the master branch is not working.
the link in the preview branch is working. so i hope it gets merged.

**Comment by almereyda** [comment]
Meanwhile `preview` has fallen behind and `master` is the most up-to-date branch.

It seems there were a lot of modifications and said `index.md` file does not exist, anymore.

Can this issue maybe be closed?
